<!DOCTYPE html>
<html>
  <head>
    <title>multi.page</title>
    <script type="text/javascript">
      var App = {
       baseUrl: 'http://multi.page/',
       module: 'application',
       controller: 'aviso',
       action: 'lista'
      }
    </script>
  </head>
  <body>
    <h1>Multi.page</h1>
    <p>Lorem ipsum</p>
    <script data-main="js/main" src="js/libs/require/require-min.js" type="text/javascript"></script>
  </body>
</html>